/**
 * Strukturerte sjekklister fra NVE-veilederen for ROS-analyser i kraftforsyningen,
 * vedlegg 1. Brukes som referansekatalog når brukeren bygger opp hendelsesregister.
 */

export type Anleggstype =
  | "vannkraftverk"
  | "transformatorstasjon"
  | "overforingsanlegg"
  | "fjernvarmeanlegg"
  | "kontrollrom"
  | "data_sambandsrom"
  | "batterirom"
  | "fysisk_sikring";

export interface Sjekklistepunkt {
  delelement: string;
  hendelse: string;
  beskrivelse?: string;
}

export interface Sjekkliste {
  anleggstype: Anleggstype;
  navn: string;
  beskrivelse: string;
  delelementer: string[];
  punkter: Sjekklistepunkt[];
}

export const SJEKKLISTER: Record<Anleggstype, Sjekkliste> = {
  vannkraftverk: {
    anleggstype: "vannkraftverk",
    navn: "Vannkraftverk (produksjonsanlegg)",
    beskrivelse:
      "Sjekkliste for produksjonsanlegg med vannvei, maskinsal og tilhørende elektriske anlegg.",
    delelementer: [
      "Inntak",
      "Trykksjakt",
      "Innløpsrør",
      "Hovedstengeventil",
      "Turbin",
      "Turbinregulator",
      "Løpehjul",
      "Generator",
      "Magnetisering",
      "Skinneanlegg",
      "Transformator",
      "Spenningstransformator",
      "Strømtransformator",
      "Effektbryter",
      "Skillebryter",
      "Jordkniv",
      "Avleder",
      "Isolator",
      "Kabler",
      "Koblingsanlegg",
      "Kontroll-/verneanlegg",
      "Batterianlegg",
      "Stasjonsforsyning (aggregat)",
      "Kjølevannsanlegg",
      "Brannsikring",
      "CO2-slokkeanlegg",
    ],
    punkter: [
      { delelement: "Trykksjakt", hendelse: "Trykksjakt kollapser" },
      { delelement: "Trykksjakt/Innløpsrør", hendelse: "Vannlekkasje" },
      { delelement: "Hovedstengeventil", hendelse: "Ventil åpner ikke" },
      { delelement: "Hovedstengeventil", hendelse: "Ventil stenger ikke" },
      { delelement: "Hovedstengeventil", hendelse: "Nødstenging" },
      { delelement: "Turbin", hendelse: "Havari" },
      { delelement: "Turbin", hendelse: "Vibrasjon" },
      { delelement: "Turbin", hendelse: "Ukontrollert rotasjon på turbin" },
      { delelement: "Turbin/Transformator", hendelse: "Oljelekkasje" },
      { delelement: "Transformator", hendelse: "Eksplosjon i transformator" },
      { delelement: "Transformator", hendelse: "Brann i transformator" },
      { delelement: "Skinneanlegg/Koblingsanlegg", hendelse: "Kortslutning" },
      { delelement: "Isolator", hendelse: "Overslag" },
      { delelement: "Effektbryter", hendelse: "Klarer ikke bryte strøm" },
      { delelement: "Effektbryter", hendelse: "Mislykket utkobling" },
      { delelement: "Skillebryter", hendelse: "Utilsiktet innkobling" },
      { delelement: "Kontroll-/verneanlegg", hendelse: "Tap av styringssystem" },
      { delelement: "Stasjonsforsyning (aggregat)", hendelse: "Feil på stasjonsforsyning" },
      { delelement: "Stasjonen", hendelse: "Brann" },
      { delelement: "Bygning", hendelse: "Stasjonen dykkes / oversvømmes" },
      { delelement: "Omgivelser", hendelse: "Skred/ras mot anlegget" },
      { delelement: "Trykksjakt/Innløpsrør", hendelse: "Rørgatebrudd" },
      { delelement: "Inntak", hendelse: "Dambrudd" },
      { delelement: "Personell", hendelse: "Arbeidsulykke under vedlikehold" },
    ],
  },

  transformatorstasjon: {
    anleggstype: "transformatorstasjon",
    navn: "Transformatorstasjon",
    beskrivelse:
      "Sjekkliste for transformatorstasjon med høyspentutstyr, vern og kontrollanlegg.",
    delelementer: [
      "Transformator",
      "Effektbryter",
      "Skillebryter",
      "Jordbryter",
      "Strømtransformator",
      "Spenningstransformator",
      "Slukkespole",
      "Samleskinne",
      "Kondensatorbatteri",
      "Avledere",
      "Isolator",
      "Gjennomføringer",
      "Endeavslutning",
      "Sikring",
      "Klemmer",
      "Kabler",
      "Muffer",
      "Innstrekkstativ",
      "Kontroll-/måleanlegg",
      "Bygninger",
    ],
    punkter: [
      { delelement: "Transformator", hendelse: "Havari" },
      { delelement: "Transformator", hendelse: "Eksplosjon" },
      { delelement: "Transformator", hendelse: "Brann" },
      { delelement: "Samleskinne", hendelse: "Ubalanse i fasespenning" },
      { delelement: "Effektbryter", hendelse: "Mislykket innkobling" },
      { delelement: "Effektbryter", hendelse: "Manglende innkobling" },
      { delelement: "Effektbryter", hendelse: "Klarer ikke bryte strøm" },
      { delelement: "Effektbryter", hendelse: "Manglende utkobling" },
      { delelement: "Skillebryter", hendelse: "Utilsiktet innkobling" },
      { delelement: "Effektbryter", hendelse: "Uønsket utkobling" },
      { delelement: "Skillebryter", hendelse: "Frakobling" },
      { delelement: "Isolator", hendelse: "Overslag" },
      { delelement: "Isolator", hendelse: "Brudd" },
      { delelement: "Innstrekkstativ", hendelse: "Fallende gjenstand" },
      { delelement: "Klemmer/Skinne", hendelse: "Varmgang" },
      { delelement: "Trafosystem", hendelse: "Over-/underspenning" },
      { delelement: "Strøm-/spenningstrafo", hendelse: "Måler feil" },
      { delelement: "Strøm-/spenningstrafo", hendelse: "Måler ikke" },
      { delelement: "Slukkespole", hendelse: "Redusert kompensering" },
      { delelement: "Samleskinne", hendelse: "Utfall" },
      { delelement: "Innstrekkstativ", hendelse: "Kantret mast" },
    ],
  },

  overforingsanlegg: {
    anleggstype: "overforingsanlegg",
    navn: "Overføringsanlegg",
    beskrivelse:
      "Sjekkliste for luftledninger, master og kabelanlegg for overføring av elektrisk energi.",
    delelementer: [
      "Mast",
      "Linje",
      "Isolator",
      "Avledere",
      "Lynavleder",
      "Jording",
      "Fundamentering/barduner",
      "Oppheng",
      "Klemmeanordning",
      "Flymarkør",
      "Kabel",
      "Muffe",
      "Trykkluftanlegg",
    ],
    punkter: [
      { delelement: "Mast", hendelse: "Kantret mast" },
      { delelement: "Mast", hendelse: "Mast knekker" },
      { delelement: "Linje", hendelse: "Brudd på linje" },
      { delelement: "Linje", hendelse: "Kordellbrudd" },
      { delelement: "Linje", hendelse: "Galoppering" },
      { delelement: "Linje", hendelse: "Vibrasjoner" },
      { delelement: "Isolator", hendelse: "Overslag" },
      { delelement: "Isolator", hendelse: "Havari av isolator" },
      { delelement: "Linje", hendelse: "Kortslutning/jordslutning" },
      { delelement: "Klemmeanordning", hendelse: "Varmgang" },
      { delelement: "Mast/Linje", hendelse: "Mekaniske skader" },
      { delelement: "Oppheng", hendelse: "Fallende gjenstand" },
      { delelement: "Kabel/Muffe", hendelse: "Oljelekkasjer" },
      { delelement: "Trykkluftanlegg", hendelse: "Lekkasje" },
    ],
  },

  fjernvarmeanlegg: {
    anleggstype: "fjernvarmeanlegg",
    navn: "Fjernvarmeanlegg",
    beskrivelse:
      "Sjekkliste for fjernvarmesentral, distribusjonsnett og tilhørende installasjoner.",
    delelementer: [
      "Kjelanlegg",
      "Varmesentral",
      "Brenselsilo",
      "Kontrollsystem",
      "Pumpe",
      "Ventil (gass/vann)",
      "Vannrenseanlegg",
      "Rør (gass)",
      "Rør (vann)",
      "Avløpsrør",
      "Transformator nettstasjon",
      "Generator",
      "Strømforsyning",
      "Kundesentral",
      "Temperaturregulator",
      "Avfallslager",
    ],
    punkter: [
      { delelement: "Anlegg", hendelse: "Frost på anlegg" },
      { delelement: "Brenselsilo", hendelse: "Antennelse av brennbart materiale" },
      { delelement: "Avfallslager", hendelse: "Brann i avfallslager" },
      { delelement: "Brenselsilo", hendelse: "Brann i brenselsilo" },
      { delelement: "Kjelanlegg", hendelse: "Svikt i kjel" },
      { delelement: "Varmesentral", hendelse: "Koking i varmesentral" },
      { delelement: "Rør (vann)", hendelse: "Koking i nett" },
      { delelement: "Kjelanlegg", hendelse: "Havari elektrokjele - knallgass" },
      { delelement: "Ventil (gass/vann)", hendelse: "Sikkerhetsventil blåser på personell" },
      { delelement: "Kjelanlegg", hendelse: "Damputslipp" },
      { delelement: "Rør (gass)", hendelse: "Gasslekkasje" },
      { delelement: "Kjelanlegg", hendelse: "Utilsiktet drenering av gasskjel" },
      { delelement: "Rør (vann)", hendelse: "Rørbrudd vann" },
      { delelement: "Rør (gass)", hendelse: "Rørbrudd gass" },
      { delelement: "Rør (vann)", hendelse: "Lekkasje i fjernvarmenett" },
      { delelement: "Kjelanlegg", hendelse: "Utslipp av luft fra gasskjel" },
      { delelement: "Anlegg", hendelse: "Utslipp (miljøforurensning)" },
      { delelement: "Avløpsrør", hendelse: "Svikt i kommunalt avløp" },
      { delelement: "Pumpe/Ventil", hendelse: "Vannlekkasje til følsomt utstyr" },
      { delelement: "Pumpe", hendelse: "Svikt i vanntilførsel" },
      { delelement: "Kontrollsystem", hendelse: "Feil på kontrollanlegg" },
      { delelement: "Temperaturregulator", hendelse: "Svikt i temperaturregulering" },
      { delelement: "Strømforsyning", hendelse: "Svikt i strømtilførsel" },
      { delelement: "Lager", hendelse: "Gassflaske faller" },
      { delelement: "Personell", hendelse: "Varme overflater (brannskader)" },
      { delelement: "Personell", hendelse: "Kuttskader" },
      { delelement: "Personell", hendelse: "Fallskader" },
    ],
  },

  kontrollrom: {
    anleggstype: "kontrollrom",
    navn: "Kontrollrom / driftssentral",
    beskrivelse:
      "Sjekkliste for kontrollrom og driftssentral inkl. bygning, brannsikring og IT-systemer.",
    delelementer: [
      "Bygning",
      "Inngang",
      "Dører",
      "Vinduer",
      "Brannalarm/-detektorer",
      "Slokkeanlegg (gass m.m.)",
      "Håndslokkeutstyr",
      "Brannfarlige materialer",
      "Sluk/avløp",
      "Kabler",
      "IT-systemer",
      "Kontrollromsutstyr",
    ],
    punkter: [
      { delelement: "Bygning", hendelse: "Brann i kontrollrom" },
      { delelement: "Bygning", hendelse: "Røykutvikling" },
      { delelement: "Sluk/avløp", hendelse: "Vannlekkasje til utstyr" },
      { delelement: "Inngang/Dører", hendelse: "Innbrudd" },
      { delelement: "Bygning", hendelse: "Hærverk" },
      { delelement: "IT-systemer", hendelse: "Svikt i IT-systemer" },
      { delelement: "Kabler", hendelse: "Strømbrudd til kontrollrom" },
      { delelement: "Kontrollromsutstyr", hendelse: "Tap av kommunikasjon" },
      { delelement: "Personell", hendelse: "Feilbetjening" },
      { delelement: "Bygning", hendelse: "Evakuering av driftssentral" },
      { delelement: "Inngang", hendelse: "Adgang fra uvedkommende" },
    ],
  },

  data_sambandsrom: {
    anleggstype: "data_sambandsrom",
    navn: "Data-/sambandsrom",
    beskrivelse:
      "Sjekkliste for datarom og sambandsrom som understøtter drift og kommunikasjon.",
    delelementer: [
      "Bygning",
      "Inngang",
      "Dører",
      "Vinduer",
      "Brannalarm/-detektorer",
      "Slokkeanlegg (gass m.m.)",
      "Håndslokkeutstyr",
      "Brannfarlige materialer",
      "Sluk/avløp",
      "Kabler",
      "IT-systemer",
      "Sambandsutstyr",
    ],
    punkter: [
      { delelement: "Bygning", hendelse: "Brann i datarom" },
      { delelement: "IT-systemer", hendelse: "Overoppheting av utstyr" },
      { delelement: "Sluk/avløp", hendelse: "Vannlekkasje" },
      { delelement: "Kabler", hendelse: "Strømbrudd" },
      { delelement: "Bygning", hendelse: "Svikt i kjøling" },
      { delelement: "Inngang", hendelse: "Sabotasje" },
      { delelement: "IT-systemer", hendelse: "Cyberangrep" },
      { delelement: "Sambandsutstyr", hendelse: "Tap av samband" },
      { delelement: "Slokkeanlegg (gass m.m.)", hendelse: "Slokkemiddel utløses uten brann" },
    ],
  },

  batterirom: {
    anleggstype: "batterirom",
    navn: "Batterirom / aggregat / nødstrøm",
    beskrivelse:
      "Sjekkliste for batterirom, nødstrømsaggregat og tilhørende drivstoffanlegg.",
    delelementer: [
      "Bygning",
      "Inngang",
      "Dører",
      "Vinduer",
      "Brannalarm/-detektorer",
      "Slokkeanlegg (gass m.m.)",
      "Håndslokkeutstyr",
      "Brannfarlige materialer",
      "Sluk/avløp",
      "Kabler (felles)",
      "Gjennomføringer",
      "Batterier",
      "Aggregat og tilkoblinger",
      "Drivstofftank",
      "Drivstoff",
      "Fysisk skille",
    ],
    punkter: [
      { delelement: "Aggregat og tilkoblinger", hendelse: "Overbelastning" },
      { delelement: "Batterier", hendelse: "Eksplosjon" },
      { delelement: "Batterier", hendelse: "Brann i batterirom" },
      { delelement: "Aggregat og tilkoblinger", hendelse: "Kobler seg ikke inn" },
      { delelement: "Drivstofftank", hendelse: "Tomt for drivstoff" },
      { delelement: "Drivstofftank", hendelse: "Drivstoff-lekkasje" },
      { delelement: "Batterier", hendelse: "Hydrogen-akkumulering" },
      { delelement: "Aggregat og tilkoblinger", hendelse: "Test av nødstrøm mislykkes" },
      { delelement: "Gjennomføringer", hendelse: "Kabelbrann via gjennomføring" },
    ],
  },

  fysisk_sikring: {
    anleggstype: "fysisk_sikring",
    navn: "Fysisk sikring (perimetersikring)",
    beskrivelse:
      "Sjekkliste for perimetersikring – porter, gjerder, bommer, overvåking og belysning.",
    delelementer: [
      "Port",
      "Portstolper inkl. feste i grunn",
      "Lås",
      "Mellomrom mellom tofløyd port",
      "Veibom",
      "Kantstein",
      "Betongblokker",
      "Gjerde",
      "Gjerdeduk",
      "Strekkstål",
      "Gitter",
      "Gjerdestolper",
      "Piggtråd",
      "Topptråd",
      "Bunntråd",
      "Overvåkings- og alarmsystemer",
      "Belysning av uteområde",
      "Høyttaleranlegg",
      "Porttelefon",
      "Observasjonsstillinger",
    ],
    punkter: [
      { delelement: "Port", hendelse: "Innbrudd via port" },
      { delelement: "Gjerde", hendelse: "Innbrudd via gjerde" },
      { delelement: "Anlegg", hendelse: "Hærverk" },
      { delelement: "Anlegg", hendelse: "Sabotasje" },
      { delelement: "Veibom", hendelse: "Påkjørsel" },
      { delelement: "Overvåkings- og alarmsystemer", hendelse: "Manglende deteksjon" },
      { delelement: "Belysning av uteområde", hendelse: "Sviktet belysning" },
      { delelement: "Port/Gjerde", hendelse: "Adgang fra uvedkommende" },
    ],
  },
};

export interface SaerskiltForhold {
  kategori: "omgivelser" | "personell" | "teknisk" | "tilsiktet";
  navn: string;
}

export const SAERSKILTE_FORHOLD: SaerskiltForhold[] = [
  // Omgivelser
  { kategori: "omgivelser", navn: "Tordenvær" },
  { kategori: "omgivelser", navn: "Vind" },
  { kategori: "omgivelser", navn: "Snø/is" },
  { kategori: "omgivelser", navn: "Snøsig" },
  { kategori: "omgivelser", navn: "Frost/tele" },
  { kategori: "omgivelser", navn: "Kvikkleire" },
  { kategori: "omgivelser", navn: "Erosjon" },
  { kategori: "omgivelser", navn: "Skred/ras" },
  { kategori: "omgivelser", navn: "Flom" },
  { kategori: "omgivelser", navn: "Salt/forurensing" },
  { kategori: "omgivelser", navn: "Fremmedlegemer" },
  { kategori: "omgivelser", navn: "Fugl/dyr" },
  { kategori: "omgivelser", navn: "Vegetasjon" },
  { kategori: "omgivelser", navn: "Brann/skogbrann" },
  { kategori: "omgivelser", navn: "Vanskelig adkomst" },

  // Personell
  { kategori: "personell", navn: "Feilbetjening" },
  { kategori: "personell", navn: "Arbeid/prøving" },
  { kategori: "personell", navn: "Trefelling" },
  { kategori: "personell", navn: "Graving/sprengning" },
  { kategori: "personell", navn: "Trafikkskade" },
  { kategori: "personell", navn: "Kompetansemangel" },
  { kategori: "personell", navn: "Sykefravær" },
  { kategori: "personell", navn: "Streik" },
  { kategori: "personell", navn: "Underleverandører" },

  // Teknisk
  { kategori: "teknisk", navn: "Aldring" },
  { kategori: "teknisk", navn: "Slitasje" },
  { kategori: "teknisk", navn: "Korrosjon" },
  { kategori: "teknisk", navn: "Lekkasje" },
  { kategori: "teknisk", navn: "Sprekk/brudd" },
  { kategori: "teknisk", navn: "Sikkerhetssystemer" },
  { kategori: "teknisk", navn: "Redundans" },
  { kategori: "teknisk", navn: "Belastning" },
  { kategori: "teknisk", navn: "Sambandsbrudd" },
  { kategori: "teknisk", navn: "Kjøling" },
  { kategori: "teknisk", navn: "Kaskadeeffekter" },
  { kategori: "teknisk", navn: "Fellesfeil" },
  { kategori: "teknisk", navn: "Branntilløp" },

  // Tilsiktet
  { kategori: "tilsiktet", navn: "Innbrudd" },
  { kategori: "tilsiktet", navn: "Hærverk" },
  { kategori: "tilsiktet", navn: "Sabotasje" },
  { kategori: "tilsiktet", navn: "Industrispionasje" },
  { kategori: "tilsiktet", navn: "Terror" },
  { kategori: "tilsiktet", navn: "IT-virus/ormer/trojanere" },
  { kategori: "tilsiktet", navn: "Evakuering av driftssentral" },
];
